/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Ellipse1Image from 'src/assets/images/Root_Ellipse_1.png';
import Polygon1Image from 'src/assets/images/Root_Polygon_1.png';
import Ellipse11Image from 'src/assets/images/Root_Ellipse_1_1.png';
import Polygon11Image from 'src/assets/images/Root_Polygon_1_1.png';
import { styled } from '@mui/material/styles';
import CoverImage from 'src/assets/images/Root_Cover.png';
import Item from 'src/components/Item/Item';

const Root1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
});

const Header = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `1px 1px 1px rgba(0, 0, 0, 0.1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `78px`,
  margin: `0px`,
});

const InnerHeaderMaxWidthC = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
  overflow: `hidden`,
});

const Logo = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Ellipse1 = styled('img')({
  height: `23px`,
  width: `23px`,
  margin: `0px`,
});

const Rectangle1 = styled('div')({
  backgroundColor: `rgba(36, 0, 255, 1)`,
  width: `10px`,
  height: `21px`,
  margin: `0px`,
});

const Polygon1 = styled('img')({
  height: `21.75px`,
  width: `25.11px`,
  margin: `0px`,
});

const Bigpath = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 6.5px`,
});

const HeroGridSm1GridMd2Ma = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `60px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
  overflow: `hidden`,
});

const Hero = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `20px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
  overflow: `hidden`,
});

const Title = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
  overflow: `hidden`,
});

const LoremIpsumDoloresSitSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(55, 55, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `900`,
  fontSize: `56px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `126.96000337600708%`,
  textTransform: `none`,
});

const LoremIpsumDoloresSitSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(36, 0, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `900`,
  fontSize: `56px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `126.96000337600708%`,
  textTransform: `none`,
});

const LoremIpsumDoloresSit = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `900`,
  fontSize: `56px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `126.96000337600708%`,
  textTransform: `none`,
  flexGrow: `1`,
  margin: `0px`,
});

const Caption = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
  overflow: `hidden`,
});

const LoremIpsumDolorSitAm = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(133, 133, 133, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  flexGrow: `1`,
  margin: `0px`,
});

const Photo = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
  overflow: `hidden`,
});

const Cover = styled('div')({
  backgroundImage: `url(${CoverImage})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  mixBlendMode: `multiply`,
  flexGrow: `1`,
  height: `386px`,
  margin: `0px`,
});

const Features = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `10px 10px 100px 10px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
  overflow: `hidden`,
});

const CraftBuildShip = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `48px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const GridGridSm1GridMd2Gr = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `34.5px 0px 0px 0px`,
  overflow: `hidden`,
});

const Item1 = styled(Item)(({ theme }) => ({
  flexGrow: `1`,
  margin: `0px`,
}));

const Item2 = styled(Item)(({ theme }) => ({
  flexGrow: `1`,
  margin: `0px`,
}));

const Item3 = styled(Item)(({ theme }) => ({
  flexGrow: `1`,
  margin: `0px`,
}));

const Caption1 = styled('div')({
  backgroundColor: `rgba(36, 0, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `100px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
  overflow: `hidden`,
});

const InnerMaxWidthCommon1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `20px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Caption2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const LoremIpsumDoloresAme = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 161, 234, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const LoremIpsumDoloresAme1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `72px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Menu = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-end`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const DoloresSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const DoloresSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Dolores = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const IpsumSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const IpsumSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Ipsum = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 10px`,
});

const LoremSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
});

const LoremSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Lorem = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 10px`,
});

const Footer = styled('div')({
  backgroundColor: `rgba(55, 55, 55, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `10px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
  overflow: `hidden`,
});

const InnerMaxWidthCommon11 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `20px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Grid = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  height: `128px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Logo1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Ellipse11 = styled('img')({
  height: `30px`,
  width: `30px`,
  margin: `0px`,
});

const Rectangle11 = styled('div')({
  backgroundColor: `rgba(36, 0, 255, 1)`,
  width: `15px`,
  height: `31px`,
  margin: `0px`,
});

const Polygon11 = styled('img')({
  height: `30.31px`,
  width: `35px`,
  margin: `0px`,
});

const Bigpath1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `36px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const MenuGridSm2GridMd4Gr = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
  overflow: `hidden`,
});

const Submenu = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
  overflow: `hidden`,
});

const Solution = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const MachineLearning = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const Decision = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const Ai = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const Submenu1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px 0px 0px 10px`,
  overflow: `hidden`,
});

const Careers = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Apply = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const Jobs = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const Culture = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const Submenu2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px 0px 0px 10px`,
  overflow: `hidden`,
});

const Docs = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const HelpCenter = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const Contact = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const Bot = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const Submenu3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px 0px 0px 10px`,
  overflow: `hidden`,
});

const Social = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Twitter = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const GitHub = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const Instagram = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

function Root(props) {
  return (
    <Root1 className={props.className}>
      <Header>
        <InnerHeaderMaxWidthC>
          <Logo>
            <Ellipse1 src={Ellipse1Image} loading="lazy" alt={'Ellipse 1'} />
            <Rectangle1></Rectangle1>
            <Polygon1 src={Polygon1Image} loading="lazy" alt={'Polygon 1'} />
          </Logo>
          <Bigpath>{`bigpath.`}</Bigpath>
        </InnerHeaderMaxWidthC>
      </Header>
      <HeroGridSm1GridMd2Ma>
        <Hero>
          <Title>
            <LoremIpsumDoloresSit>
              <LoremIpsumDoloresSitSpan1>{`Lorem ipsum `}</LoremIpsumDoloresSitSpan1>
              <LoremIpsumDoloresSitSpan2>{`dolores sit amet`}</LoremIpsumDoloresSitSpan2>
            </LoremIpsumDoloresSit>
          </Title>
          <Caption>
            <LoremIpsumDolorSitAm>
              {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis posuere pellentesque `}
            </LoremIpsumDolorSitAm>
          </Caption>
        </Hero>
        <Photo>
          <Cover></Cover>
        </Photo>
      </HeroGridSm1GridMd2Ma>
      <Features>
        <CraftBuildShip>{`Craft, Build & ship`}</CraftBuildShip>
        <GridGridSm1GridMd2Gr>
          <Item1 />
          <Item2 />
          <Item3 />
        </GridGridSm1GridMd2Gr>
      </Features>
      <Caption1>
        <InnerMaxWidthCommon1>
          <Caption2>
            <LoremIpsumDoloresAme>
              {`Lorem ipsum dolores amet.`}
            </LoremIpsumDoloresAme>
            <LoremIpsumDoloresAme1>
              {`Lorem ipsum dolores amet.`}
            </LoremIpsumDoloresAme1>
          </Caption2>
          <Menu>
            <Dolores>
              <DoloresSpan1>{`Twitter`}</DoloresSpan1>
              <DoloresSpan2>{`.`}</DoloresSpan2>
            </Dolores>
            <Ipsum>
              <IpsumSpan1>{`Instagram`}</IpsumSpan1>
              <IpsumSpan2>{`.`}</IpsumSpan2>
            </Ipsum>
            <Lorem>
              <LoremSpan1>{`Facebook`}</LoremSpan1>
              <LoremSpan2>{`.`}</LoremSpan2>
            </Lorem>
          </Menu>
        </InnerMaxWidthCommon1>
      </Caption1>
      <Footer>
        <InnerMaxWidthCommon11>
          <Grid>
            <Logo1>
              <Ellipse11
                src={Ellipse11Image}
                loading="lazy"
                alt={'Ellipse 1'}
              />
              <Rectangle11></Rectangle11>
              <Polygon11
                src={Polygon11Image}
                loading="lazy"
                alt={'Polygon 1'}
              />
            </Logo1>
            <Bigpath1>{`bigpath.`}</Bigpath1>
          </Grid>
          <MenuGridSm2GridMd4Gr>
            <Submenu>
              <Solution>{`Solution`}</Solution>
              <MachineLearning>{`Machine Learning`}</MachineLearning>
              <Decision>{`Decision`}</Decision>
              <Ai>{`AI`}</Ai>
            </Submenu>
            <Submenu1>
              <Careers>{`Careers`}</Careers>
              <Apply>{`Apply`}</Apply>
              <Jobs>{`Jobs`}</Jobs>
              <Culture>{`Culture`}</Culture>
            </Submenu1>
            <Submenu2>
              <Docs>{`Docs`}</Docs>
              <HelpCenter>{`Help Center`}</HelpCenter>
              <Contact>{`Contact`}</Contact>
              <Bot>{`Bot`}</Bot>
            </Submenu2>
            <Submenu3>
              <Social>{`Social`}</Social>
              <Twitter>{`Twitter`}</Twitter>
              <GitHub>{`GitHub`}</GitHub>
              <Instagram>{`Instagram`}</Instagram>
            </Submenu3>
          </MenuGridSm2GridMd4Gr>
        </InnerMaxWidthCommon11>
      </Footer>
    </Root1>
  );
}

export default Root;
