/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

const Frame11 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `26px 40px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
  width: 'fit-content',
});

const Frame5 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Rectangle1 = styled('div')({
  backgroundColor: `rgba(211, 48, 48, 1)`,
  height: `124px`,
  width: `1336px`,
  margin: `0px`,
});

const Frame3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `20px 0px 0px 0px`,
});

const Rectangle2 = styled('div')({
  backgroundColor: `rgba(43, 215, 70, 1)`,
  height: `473px`,
  width: `1334px`,
  margin: `0px`,
});

const Frame4 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `20px 0px 0px 0px`,
});

const Rectangle3 = styled('div')({
  backgroundColor: `rgba(154, 156, 216, 1)`,
  height: `272px`,
  width: `1334px`,
  margin: `0px`,
});

function Frame1(props) {
  return (
    <Frame11 className={props.className}>
      <Frame5>
        <Frame2>
          <Rectangle1></Rectangle1>
        </Frame2>
        <Frame3>
          <Rectangle2></Rectangle2>
        </Frame3>
        <Frame4>
          <Rectangle3></Rectangle3>
        </Frame4>
      </Frame5>
    </Frame11>
  );
}

export default Frame1;
